/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPaymentStatusRouteImport } from './routes/api/payment-status'
import { Route as ApiSepayWebhookRouteImport } from './routes/api/sepay-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentStatusRoute = ApiPaymentStatusRouteImport.update({
  id: '/api/payment-status',
  path: '/api/payment-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSepayWebhookRoute = ApiSepayWebhookRouteImport.update({
  id: '/api/sepay-webhook',
  path: '/api/sepay-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/payment-status': typeof ApiPaymentStatusRoute
  '/api/sepay-webhook': typeof ApiSepayWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/payment-status': typeof ApiPaymentStatusRoute
  '/api/sepay-webhook': typeof ApiSepayWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/payment-status': typeof ApiPaymentStatusRoute
  '/api/sepay-webhook': typeof ApiSepayWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/payment-status' | '/api/sepay-webhook'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/payment-status' | '/api/sepay-webhook'
  id: '__root__' | '/' | '/api/payment-status' | '/api/sepay-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPaymentStatusRoute: typeof ApiPaymentStatusRoute
  ApiSepayWebhookRoute: typeof ApiSepayWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment-status': {
      id: '/api/payment-status'
      path: '/api/payment-status'
      fullPath: '/api/payment-status'
      preLoaderRoute: typeof ApiPaymentStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sepay-webhook': {
      id: '/api/sepay-webhook'
      path: '/api/sepay-webhook'
      fullPath: '/api/sepay-webhook'
      preLoaderRoute: typeof ApiSepayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPaymentStatusRoute: ApiPaymentStatusRoute,
  ApiSepayWebhookRoute: ApiSepayWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
